SaldoVacaciones/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using SaldoVacaciones.Models;
using SaldoVacaciones.Datos;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.WebSockets;
using Microsoft.AspNetCore.Authorization;

namespace SaldoVacaciones.Controllers
{
    [Authorize]
    public class EmpleadoController : Controller
    {
        EmpleadoDatos _EmpleadoDatos = new EmpleadoDatos();
        PuestoDatos _PuestoDatos = new PuestoDatos();
        ErrorDatos _ErrorDatos = new ErrorDatos();


        public IActionResult Listar()
        {
            var oLista = _EmpleadoDatos.Listar("");
            return View(oLista);
        }
        [HttpPost]
        public IActionResult Listar(string campo)
        {
            var oLista = _EmpleadoDatos.Listar(campo);
            return View(oLista);
        }

        public IActionResult Editar(string ValorDocumentoIdentidad)
        {
            var oEmpleado = _EmpleadoDatos.Obtener(ValorDocumentoIdentidad);
            var oLista = _PuestoDatos.ListarPuesto();
            List<string> puestos = new List<string>();
            for (int i = 0; i < oLista.Count; i++) {
                puestos.Add(oLista[i].Nombre);
            }
            ViewBag.Puestos = new SelectList(puestos);
            return View(oEmpleado);
        }
        [HttpPost]
        public IActionResult Editar(EmpleadoModel oEmpleado)
        {
            if (!ModelState.IsValid)
            {
                var oLista = _PuestoDatos.ListarPuesto();
                List<string> puestos = new List<string>();
                for (int i = 0; i < oLista.Count; i++)
                {
                    puestos.Add(oLista[i].Nombre);
                }
                ViewBag.Puestos = new SelectList(puestos);
                return View();
            }
            var resultado = _EmpleadoDatos.Editar(oEmpleado);
            if (resultado == 0)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                var oLista = _PuestoDatos.ListarPuesto();
                List<string> puestos = new List<string>();
                for (int i = 0; i < oLista.Count; i++)
                {
                    puestos.Add(oLista[i].Nombre);
                }
                ViewBag.Puestos = new SelectList(puestos);
                var oError = _ErrorDatos.ObtenerError(resultado);

                TempData["ErrorMessage"] = "Error: " + oError.Codigo + " Descripcion: " + oError.Descripcion;
                return View(); // sino se queda en el mismo formulario

            }
        }

        public IActionResult Insertar()
        { // Solo devuelve la vista
            var oLista = _PuestoDatos.ListarPuesto();
            List<string> puestos = new List<string>();
            for (int i = 0; i < oLista.Count; i++)
            {
                puestos.Add(oLista[i].Nombre);
            }
            ViewBag.Puestos = new SelectList(puestos);
            return View();
        }

        [HttpPost]
        public IActionResult Insertar(EmpleadoModel oEmpleado)
        { //

            if (!ModelState.IsValid) {
                var oLista = _PuestoDatos.ListarPuesto();
                List<string> puestos = new List<string>();
                for (int i = 0; i < oLista.Count; i++)
                {
                    puestos.Add(oLista[i].Nombre);
                }
                ViewBag.Puestos = new SelectList(puestos);
                return View();
            }
            var resultado = _EmpleadoDatos.Insertar(oEmpleado);
            if (resultado == 0)
            {
                return RedirectToAction("Listar");
            }
            else {
                var oLista = _PuestoDatos.ListarPuesto();
                List<string> puestos = new List<string>();
                for (int i = 0; i < oLista.Count; i++)
                {
                    puestos.Add(oLista[i].Nombre);
                }
                ViewBag.Puestos = new SelectList(puestos);
                var oError = _ErrorDatos.ObtenerError(resultado);
                
                TempData["ErrorMessage"] = "Error: " + oError.Codigo + " Descripcion: " + oError.Descripcion;
                return View(); // sino se queda en el mismo formulario

            }
        }
        public IActionResult Eliminar(string ValorDocumentoIdentidad)
        {
            var oEmpleado = _EmpleadoDatos.Obtener(ValorDocumentoIdentidad);
            return View(oEmpleado);
        }
        [HttpPost]
        public IActionResult Eliminar(EmpleadoModel oEmpleado)
        {
            var resultado = _EmpleadoDatos.Eliminar(oEmpleado.ValorDocumentoIdentidad);
            if (resultado)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View(); // sino se queda en el mismo formulario

            }
        }

        public IActionResult Consultar(EmpleadoModel oEmpleado)
        {
            var resultado = _EmpleadoDatos.Eliminar(oEmpleado.ValorDocumentoIdentidad);
            if (resultado)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View(); // sino se queda en el mismo formulario

            }
        }

    }
}

SaldoVacaciones/Views/Empleado/Editar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Empleado
    </div>
    <div class="card-body">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }

        <form asp-action="Editar" asp-controller="Empleado" method="post">
            <input asp-for="Id" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Valor Documento de Identidad</label>
                <input asp-for="ValorDocumentoIdentidad" class="form-control">
                <span asp-validation-for="ValorDocumentoIdentidad" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Puestos</label>
                @Html.DropDownListFor(model => model.NombrePuesto, ViewBag.Puestos as SelectList, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-primary btn-abrir-modal"><i class="bi bi-save"></i> Guardar</button>
            <a asp-action="Listar" asp-controller="Empleado" class="btn btn-warning"><i class="bi bi-arrow-return-left"></i> Regresar</a>
        </form>
    </div>
</div>

SaldoVacaciones/Views/Empleado/Eliminar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Eliminar Empleado
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Empleado" method="post">
            <input asp-for="ValorDocumentoIdentidad" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el empleado:  @Model.Nombre          @Html.DisplayTextFor(m => m.ValorDocumentoIdentidad)?
            </div>

            <button type="submit" class="btn btn-danger btn-abrir-modal">Eliminar</button>
            <a asp-action="Listar" asp-controller="Empleado" class="btn btn-warning">Regresar</a>
        </form>
    </div>
</div>

SaldoVacaciones/Views/Empleado/Insertar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Insertar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Insertar Empleado
    </div>
    <div class="card-body">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }

        <form asp-action="Insertar" asp-controller="Empleado" method="post">
            <div class="mb-3">
                <label class="form-label">Valor Documento de Identidad</label>
                <input asp-for="ValorDocumentoIdentidad" class="form-control">
                <span asp-validation-for="ValorDocumentoIdentidad" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Puesto</label>
                @Html.DropDownListFor(model => model.NombrePuesto, ViewBag.Puestos as SelectList, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-primary btn-abrir-modal">Insertar</button>
            <a asp-action="Listar" asp-controller="Empleado" class="btn btn-warning">Regresar</a>
        </form>
    </div>
</div>

SaldoVacaciones/Views/Empleado/Listar.cshtml
@model List<EmpleadoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista Empleados</h1>
<div class="card">
    <div class="card-body">
        <form asp-action="Listar" asp-controller="Empleado" method="post" class="row g-3 align-items-center">
            <div class="col">
                <label for="campo" class="visually-hidden"> Filtrar</label>
                <input type="text" id="campo" name="campo" class="form-control" placeholder="Filtrar">
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-3"><i class="bi bi-search"></i> Buscar</button>
            </div>
        </form>
        <table class="table table-bordered" bgcolor="white" width="700">
            <thead>
                <tr bgcolor="grey">
                    <th>Nombre</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) // c# en html
                {// se crea una nueva fila
                    <tr>
                        <!-- Se inserta los datos del modelo-->
                        <td>@item.Nombre</td>
                        <td>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-info btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal-@item.ValorDocumentoIdentidad">
                                <i class="bi bi-eye"></i> Consultar
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal-@item.ValorDocumentoIdentidad" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Detalles de @item.Nombre</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Nombre Completo: @item.Nombre</p>
                                            <p>Documento de Identidad: @item.ValorDocumentoIdentidad</p>
                                            <p>Nombre del Puesto: @item.NombrePuesto</p>
                                            <p>Saldo de Vacaciones: @item.SaldoVacaciones</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <a asp-action="Editar" asp-controller="Empleado" class="btn btn-primary btn-sm" asp-route-ValorDocumentoIdentidad="@item.ValorDocumentoIdentidad"><i class="bi bi-pencil-square"></i> Editar</a>
                            <a asp-action="Eliminar" asp-controller="Empleado" class="btn btn-danger btn-sm" asp-route-ValorDocumentoIdentidad="@item.ValorDocumentoIdentidad"><i class="bi bi-trash-fill"></i> Eliminar</a>
                            <a asp-action="ListarMovimientos" asp-controller="Movimiento" class="btn btn-dark btn-sm" asp-route-ValorDocumentoIdentidad="@item.ValorDocumentoIdentidad"><i class="bi bi-wallet2"></i> Ver Movimientos</a>


                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <a asp-action="Insertar" asp-controller="Empleado" class="btn btn-success"><i class="bi bi-plus-circle"></i> Insertar</a>
    </div>
</div>